"""闪时送云端名单导入兼容门面：实现见 import_models / roster / archive / service。"""
from __future__ import annotations

from app.ordering.import_models import (
    CELL_MARK,
    COL_ADDRESS,
    COL_NAME,
    COL_PHONE,
    DATE_COL,
    DATE_ROW,
    DayOrders,
    FIRST_DATA_ROW,
    ImportRefused,
    MealImport,
)
from app.ordering.roster import (
    SKIP_ADDRESSES,
    SSS_SHEET_SOURCES,
    _MAX_PROBLEM_ROWS,
    _PHONE_RE,
    _SKIP_ADDRESS_KEYS,
    _WHITESPACE_RE,
    _clean_text,
    _cloud_error,
    _log,
    address_group,
    check_target_day,
    collect_day_orders,
    normalise_phone,
    ordering_target_date,
    read_cloud_meal,
    should_skip_address,
    validate_orders,
)
from app.ordering.archive import (
    archive_to_excel,
)
from app.ordering.service import (
    prepare_day_orders,
)
__all__ = [
    "CELL_MARK",
    "COL_ADDRESS",
    "COL_NAME",
    "COL_PHONE",
    "DATE_COL",
    "DATE_ROW",
    "DayOrders",
    "FIRST_DATA_ROW",
    "ImportRefused",
    "MealImport",
    "SKIP_ADDRESSES",
    "SSS_SHEET_SOURCES",
    "_MAX_PROBLEM_ROWS",
    "_PHONE_RE",
    "_SKIP_ADDRESS_KEYS",
    "_WHITESPACE_RE",
    "_clean_text",
    "_cloud_error",
    "_log",
    "address_group",
    "archive_to_excel",
    "check_target_day",
    "collect_day_orders",
    "normalise_phone",
    "ordering_target_date",
    "prepare_day_orders",
    "read_cloud_meal",
    "should_skip_address",
    "validate_orders",
]
